"""Initial PostgreSQL schema for logs and threat_alerts

Revision ID: dad67c66e911
Revises: 
Create Date: 2026-08-23 14:03:00.366982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad67c66e911'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('destination_ip', sa.String(length=45), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_event_type'), 'logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_logs_severity'), 'logs', ['severity'], unique=False)
    op.create_index(op.f('ix_logs_source_ip'), 'logs', ['source_ip'], unique=False)
    op.create_table('threat_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('threat_type', sa.String(length=50), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_alerts_threat_type'), 'threat_alerts', ['threat_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_alerts_threat_type'), table_name='threat_alerts')
    op.drop_table('threat_alerts')
    op.drop_index(op.f('ix_logs_source_ip'), table_name='logs')
    op.drop_index(op.f('ix_logs_severity'), table_name='logs')
    op.drop_index(op.f('ix_logs_event_type'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
